/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.CitaController;
import MODELO.Cita;
import MODELO.Tratamiento;
import MODELO.Veterinario;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AtencionVista extends javax.swing.JPanel {

    private CitaController citaController;//crear un private CitaController 

    /**
     * Creates new form AtencionVista
     */
    public AtencionVista() {
        initComponents();
    }

    public AtencionVista(CitaController citaController) {
        this();
        this.citaController = citaController;
        cboVeterinario.setEnabled(false);
        habilitarTratamiento(false);
    }

    /*private void cargarVeterinarios() {

        cboVeterinario.removeAllItems();

        String[] nombres = controladorVeterinario.obtenerNombresVeterinarios();

        for (String nombre : nombres) {
            cboVeterinario.addItem(nombre);
        }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        checkboxTratamiento = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnBuscarCita = new javax.swing.JButton();
        txtDniTutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboVeterinario = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtFrecuencia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIndicaciones = new javax.swing.JTextField();
        btnGuardarAtencion = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnAtenderSiguiente = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ATENCION DE CITAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        checkboxTratamiento.setText("Requiere Tratamiento");
        checkboxTratamiento.addActionListener(this::checkboxTratamientoActionPerformed);

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnBuscarCita.setText("Buscar Cita");
        btnBuscarCita.addActionListener(this::btnBuscarCitaActionPerformed);

        jLabel3.setText("DNI del tutor:");

        jLabel4.setText("Asignar Veterinario:");

        cboVeterinario.addActionListener(this::cboVeterinarioActionPerformed);

        jLabel5.setText("Diagnostico:");

        txtDiagnostico.setColumns(20);
        txtDiagnostico.setRows(5);
        jScrollPane2.setViewportView(txtDiagnostico);

        jLabel6.setText("Observaciones:");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane3.setViewportView(txtObservaciones);

        jLabel7.setText("Resultados:");

        jLabel8.setText("Medicamento:");

        jLabel9.setText("Duracion(dias):");

        jLabel10.setText("Frecuencia:");

        jLabel11.setText("Indicaciones:");

        btnGuardarAtencion.setText("Guardar Atencion");
        btnGuardarAtencion.addActionListener(this::btnGuardarAtencionActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnAtenderSiguiente.setText("Atender Siguiente");
        btnAtenderSiguiente.addActionListener(this::btnAtenderSiguienteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIndicaciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFrecuencia)
                            .addComponent(txtDuracion)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMedicamento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkboxTratamiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardarAtencion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDniTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarCita))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addGap(39, 39, 39)
                        .addComponent(btnAtenderSiguiente)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarCita)
                            .addComponent(txtDniTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnAtenderSiguiente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkboxTratamiento)
                            .addComponent(btnGuardarAtencion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtIndicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboVeterinarioActionPerformed

    private void btnBuscarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCitaActionPerformed
        if (citaController == null) {
            return;
        }
        Cita cita = citaController.buscarCitaPorDniTutor(txtDniTutor.getText().trim());
        txtResultado.setText(cita == null ? "No se encontro una cita para ese tutor."
                : "Cita ID: " + cita.getIdCita() + "\nEstado: " + cita.getEstado()
                + "\nMascota: " + cita.getMascota().getNombre());
    }//GEN-LAST:event_btnBuscarCitaActionPerformed

    private void checkboxTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxTratamientoActionPerformed
        habilitarTratamiento(checkboxTratamiento.isSelected());
    }//GEN-LAST:event_checkboxTratamientoActionPerformed

    private void btnGuardarAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAtencionActionPerformed
        if (citaController == null || citaController.obtenerSiguienteCita() == null) {
            JOptionPane.showMessageDialog(this, "Primero cargue la siguiente cita.");
            return;
        }
        if (txtDiagnostico.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el diagnostico.");
            return;
        }
        Tratamiento tratamiento = null;
        if (checkboxTratamiento.isSelected()) try {
            tratamiento = new Tratamiento(0, txtMedicamento.getText().trim(), Integer.parseInt(txtDuracion.getText().trim()), txtFrecuencia.getText().trim(), txtIndicaciones.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Duracion invalida.");
            return;
        }
        boolean ok = citaController.atenderSiguienteCita(txtDiagnostico.getText().trim(), txtObservaciones.getText().trim(), tratamiento);
        txtResultado.setText(ok ? "Atencion guardada e historial clinico generado." : "No se pudo guardar la atencion.");
        if (ok) {
            limpiar();
        }

    }//GEN-LAST:event_btnGuardarAtencionActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAtenderSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderSiguienteActionPerformed
        /*if (citaController == null) {
            return;
        }
        Cita cita = citaController.obtenerSiguienteCita();
        if (cita == null) {
            txtResultado.setText("No hay citas en cola.");
            return;
        }
        txtDniTutor.setText(cita.getTutor().getDni());
        DefaultComboBoxModel<Veterinario> modelo = new DefaultComboBoxModel<>();
        modelo.addElement(cita.getVeterinario());
        cboVeterinario.setModel(modelo);
        cboVeterinario.setRenderer(new javax.swing.DefaultListCellRenderer() {
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> l, Object v, int i, boolean s, boolean f) {
                super.getListCellRendererComponent(l, ((Veterinario) v).getNombre() + " (" + ((Veterinario) v).getCmpv() + ")", i, s, f);
                return this;
            }
        });
        txtResultado.setText("Atendiendo cita ID: " + cita.getIdCita() + "\nMascota: " + cita.getMascota().getNombre() + "\nMotivo: " + cita.getMotivo());*/
        if (citaController == null) {
            return;
        }
        Cita cita = citaController.obtenerSiguienteCita();
        if (cita == null) {
            txtResultado.setText("No hay citas en cola.");
            return;
        }
        txtDniTutor.setText(cita.getTutor().getDni());

        DefaultComboBoxModel<Veterinario> modelo = new DefaultComboBoxModel<>();
        modelo.addElement(cita.getVeterinario());
        cboVeterinario.setModel(modelo);

        // RENDERIZADOR BLINDADO CONTRA NULOS
        cboVeterinario.setRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> l, Object v, int i, boolean s, boolean f) {
                // Validamos si el valor recibido es nulo
                if (v == null) {
                    super.getListCellRendererComponent(l, "Sin asignar", i, s, f);
                } else {
                    Veterinario vet = (Veterinario) v;
                    String texto = vet.getNombre() + " (" + vet.getCmpv() + ")";
                    super.getListCellRendererComponent(l, texto, i, s, f);
                }
                return this;
            }
        });

        txtResultado.setText("Atendiendo cita ID: " + cita.getIdCita()
                + "\nMascota: " + cita.getMascota().getNombre()
                + "\nMotivo: " + cita.getMotivo());

    }//GEN-LAST:event_btnAtenderSiguienteActionPerformed

    private void habilitarTratamiento(boolean activo) {
        txtMedicamento.setEnabled(activo);
        txtDuracion.setEnabled(activo);
        txtFrecuencia.setEnabled(activo);
        txtIndicaciones.setEnabled(activo);
    }

    private void limpiar() {
        txtDniTutor.setText("");
        txtDiagnostico.setText("");
        txtObservaciones.setText("");
        txtMedicamento.setText("");
        txtDuracion.setText("");
        txtFrecuencia.setText("");
        txtIndicaciones.setText("");
        checkboxTratamiento.setSelected(false);
        habilitarTratamiento(false);
        cboVeterinario.setModel(new DefaultComboBoxModel<>());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtenderSiguiente;
    private javax.swing.JButton btnBuscarCita;
    private javax.swing.JButton btnGuardarAtencion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<Veterinario> cboVeterinario;
    private javax.swing.JCheckBox checkboxTratamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JTextField txtDniTutor;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtFrecuencia;
    private javax.swing.JTextField txtIndicaciones;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
