/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CitaController;
import Controlador.HistorialController;
import Controlador.MascotaController;
import Controlador.ServicioController;
import Controlador.TutorController;
import Controlador.VeterinarioController;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class dashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard.class.getName());

    private final TutorController tutorController;
    private final MascotaController mascotaController;
    private final VeterinarioController veterinarioController;
    private final HistorialController historialController;
    private final CitaController citaController;
    private final ServicioController servicioController;

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();

        // Se crean una única vez al iniciar el sistema.
        historialController = new HistorialController();
        tutorController = new TutorController();
        mascotaController = new MascotaController();
        veterinarioController = new VeterinarioController();
        servicioController = new ServicioController();

        // CitaController necesita HistorialController al atender una cita.
        citaController = new CitaController(historialController);

        // Vista inicial.
        mostrarPanel(new AtencionVista());
    }

    // Cargar la vista de inicio por defecto al abrir la aplicación        
    private void mostrarPanel(JPanel vista) {
        panelContenido.removeAll();
        panelContenido.add(vista, java.awt.BorderLayout.CENTER);
        panelContenido.revalidate();
        panelContenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        btnRegistroTutor = new javax.swing.JButton();
        btnRegistroMascota = new javax.swing.JButton();
        btnRegistroVeterinario = new javax.swing.JButton();
        btnRegistroCitas = new javax.swing.JButton();
        btnHistoriaVeterinaria = new javax.swing.JButton();
        btnAtencionCitas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelTitulo.setBackground(new java.awt.Color(0, 0, 204));
        panelTitulo.setPreferredSize(new java.awt.Dimension(672, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSULTORIO PETIPET");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(121, 121, 121))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelTitulo, java.awt.BorderLayout.PAGE_START);

        panelContenido.setLayout(new java.awt.BorderLayout());
        panelPrincipal.add(panelContenido, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        panelMenu.setBackground(new java.awt.Color(0, 51, 255));
        panelMenu.setPreferredSize(new java.awt.Dimension(180, 535));

        btnRegistroTutor.setText("REGISTRO TUTOR");
        btnRegistroTutor.addActionListener(this::btnRegistroTutorActionPerformed);

        btnRegistroMascota.setText("REGISTRO MASCOTA");
        btnRegistroMascota.addActionListener(this::btnRegistroMascotaActionPerformed);

        btnRegistroVeterinario.setText("REGISTRO VETERINARIO");
        btnRegistroVeterinario.addActionListener(this::btnRegistroVeterinarioActionPerformed);

        btnRegistroCitas.setText("REGISTRO DE CITAS");
        btnRegistroCitas.setPreferredSize(new java.awt.Dimension(156, 23));
        btnRegistroCitas.addActionListener(this::btnRegistroCitasActionPerformed);

        btnHistoriaVeterinaria.setText("HISTORIA VETERINARIA");
        btnHistoriaVeterinaria.addActionListener(this::btnHistoriaVeterinariaActionPerformed);

        btnAtencionCitas.setText("ATENCION CITAS");
        btnAtencionCitas.addActionListener(this::btnAtencionCitasActionPerformed);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRegistroTutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRegistroVeterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistroMascota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistroCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHistoriaVeterinaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtencionCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(680, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnRegistroTutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistroMascota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistroVeterinario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtencionCitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistroCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHistoriaVeterinaria)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroTutorActionPerformed
        mostrarPanel(new RegistroTutorVista(tutorController));
    }//GEN-LAST:event_btnRegistroTutorActionPerformed

    private void btnRegistroMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroMascotaActionPerformed
        mostrarPanel(new RegistroMascotaVista(tutorController, mascotaController));
    }//GEN-LAST:event_btnRegistroMascotaActionPerformed

    private void btnHistoriaVeterinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaVeterinariaActionPerformed
        mostrarPanel(new HistoriaVista(historialController, mascotaController));
    }//GEN-LAST:event_btnHistoriaVeterinariaActionPerformed

    private void btnRegistroVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroVeterinarioActionPerformed
        mostrarPanel(new RegistroVeterinarioVista(veterinarioController));
    }//GEN-LAST:event_btnRegistroVeterinarioActionPerformed

    private void btnRegistroCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroCitasActionPerformed
        mostrarPanel(new CitasVista(tutorController, mascotaController, veterinarioController, servicioController, citaController));
    }//GEN-LAST:event_btnRegistroCitasActionPerformed

    private void btnAtencionCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtencionCitasActionPerformed
        mostrarPanel(new AtencionVista(citaController));
    }//GEN-LAST:event_btnAtencionCitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtencionCitas;
    private javax.swing.JButton btnHistoriaVeterinaria;
    private javax.swing.JButton btnRegistroCitas;
    private javax.swing.JButton btnRegistroMascota;
    private javax.swing.JButton btnRegistroTutor;
    private javax.swing.JButton btnRegistroVeterinario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
