/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.HistorialController;
import Controlador.MascotaController;
import ESTRUCTURAS.Nodo;
import MODELO.HistorialClinicoVeterinario;
import MODELO.Mascota;
import MODELO.Tratamiento;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class HistoriaVista extends javax.swing.JPanel {

    private HistorialController historialController;
    private MascotaController mascotaController;

    /**
     * Creates new form HistoriaVista
     */
    public HistoriaVista() {
        initComponents();
    }

    public HistoriaVista(HistorialController historialController, MascotaController mascotaController) {
        this();
        this.historialController = historialController;
        this.mascotaController = mascotaController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtIdMascota = new javax.swing.JTextField();
        btnObtenerHistorialMascota = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("HISTORIAL CLINICO VETERINARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jLabel2.setText("ID de la mascota:");

        btnObtenerHistorialMascota.setText("Obtener Historial");
        btnObtenerHistorialMascota.addActionListener(this::btnObtenerHistorialMascotaActionPerformed);

        btnMostrarTodos.setText("Mostrar Todo los Historiales");
        btnMostrarTodos.addActionListener(this::btnMostrarTodosActionPerformed);

        jButton1.setText("Historial reciente");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdMascota))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(btnObtenerHistorialMascota))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMostrarTodos)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtIdMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMostrarTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnObtenerHistorialMascota)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnObtenerHistorialMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerHistorialMascotaActionPerformed
        try {
            int id = Integer.parseInt(txtIdMascota.getText().trim());
            Mascota mascota = mascotaController.buscarMascotaPorId(id);
            if (mascota == null) {
                txtResultado.setText("No existe una mascota con ese ID.");
                return;
            }
            StringBuilder salida = new StringBuilder("MASCOTA: ").append(mascota.getNombre()).append("\n\n");
            boolean encontro = false;
            Nodo<HistorialClinicoVeterinario> actual = historialController.getHistoriales().getPrimero();
            while (actual != null) {
                HistorialClinicoVeterinario h = actual.getDato();
                if (h.getMascota().getIdMascota() == id) {
                    salida.append(describir(h)).append("\n----------------\n");
                    encontro = true;
                }
                actual = actual.getSiguiente();
            }
            if (!encontro) {
                salida.append("No tiene atenciones registradas.");
            }
            txtResultado.setText(salida.toString());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID de mascota valido.");
        }

    }//GEN-LAST:event_btnObtenerHistorialMascotaActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        StringBuilder salida = new StringBuilder("TODOS LOS HISTORIALES\n\n");
        Nodo<HistorialClinicoVeterinario> actual = historialController.getHistoriales().getPrimero();
        if (actual == null) {
            salida.append("No hay historiales registrados.");
        }
        while (actual != null) {
            salida.append(describir(actual.getDato())).append("\n----------------\n");
            actual = actual.getSiguiente();
        }
        txtResultado.setText(salida.toString());

    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HistorialClinicoVeterinario reciente = historialController.obtenerHistorialReciente();
        txtResultado.setText(reciente == null ? "No hay historiales registrados." : "HISTORIAL RECIENTE\n\n" + describir(reciente));

    }//GEN-LAST:event_jButton1ActionPerformed

    private String describir(HistorialClinicoVeterinario h) {
        Tratamiento t = h.getTratamiento();
        return "Fecha: " + h.getFecha() + "\nMascota: " + h.getMascota().getNombre() + "\nVeterinario: " + h.getVeterinario().getNombre() + "\nDiagnostico: " + h.getDiagnostico() + "\nObservaciones: " + h.getObservaciones() + "\nTratamiento: " + (t == null ? "Ninguno" : t.getMedicamento() + " - " + t.getFrecuencia());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnObtenerHistorialMascota;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdMascota;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
