/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Controlador.MascotaController;
import Controlador.TutorController;
import ESTRUCTURAS.NodoDoble;
import MODELO.Mascota;
import MODELO.RegistroTutor;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class RegistroMascotaVista extends javax.swing.JPanel {
    
    private TutorController tutorController;
    private MascotaController mascotaController;
    
    /**
     * Creates new form RegistroMascotaVista
     */
    public RegistroMascotaVista() {
        initComponents();
    }
    public RegistroMascotaVista(TutorController tutorController, MascotaController mascotaController) {
        this();
        this.tutorController = tutorController;
        this.mascotaController = mascotaController;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEspecie = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDniBuscar = new javax.swing.JTextField();

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE MASCOTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel2.setText("Nombre:");

        jLabel3.setText("Especie:");

        jLabel4.setText("Edad:");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtEdad.addActionListener(this::txtEdadActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jLabel5.setText("Dni del Tutor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDniBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(txtNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtDniBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrar)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnBuscar)
                            .addComponent(btnEliminar))
                        .addGap(36, 36, 36))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!controladoresDisponibles() || texto(txtDniBuscar).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el DNI del tutor.");
            return;
        }

        RegistroTutor tutor = tutorController.buscarTutorPorDni(texto(txtDniBuscar));
        if (tutor == null) {
            txtResultado.setText("No existe un tutor con ese DNI.");
            return;
        }

        StringBuilder resultado = new StringBuilder("TUTOR: ")
                .append(tutor.getNombre()).append(" ")
                .append(tutor.getApellidoPaterno()).append("\n\nMASCOTAS:\n");
        boolean encontroMascotas = false;
        NodoDoble<Mascota> actual = mascotaController.getMascotas().getPrimero();
        while (actual != null) {
            Mascota mascota = actual.getDato();
            if (mascota.getTutor() != null
                    && tutor.getDni().equals(mascota.getTutor().getDni())) {
                resultado.append(describirMascota(mascota)).append("\n\n");
                encontroMascotas = true;
            }
            actual = actual.getSiguiente();
        }
        if (!encontroMascotas) {
            resultado.append("No hay mascotas registradas para este tutor.");
        }
        txtResultado.setText(resultado.toString());
    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!controladoresDisponibles()) {
            return;
        }
        Mascota mascota = solicitarMascotaDelTutor("Ingrese el ID de la mascota a eliminar:");
        if (mascota == null) {
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Desea eliminar a " + mascota.getNombre() + "?",
                "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            boolean eliminada = mascotaController.eliminarMascota(mascota.getIdMascota());
            txtResultado.setText(eliminada ? "Mascota eliminada correctamente."
                    : "No se pudo eliminar la mascota.");
            if (eliminada) {
                limpiarCamposMascota();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //buscarTutorPorDni(String dni);        
        if (!controladoresDisponibles() || !camposMascotaCompletos()) {
            return;
        }

        RegistroTutor tutor = tutorController.buscarTutorPorDni(texto(txtDniBuscar));
        if (tutor == null) {
            JOptionPane.showMessageDialog(this,
                    "Primero debe registrar o ingresar un tutor existente con ese DNI.");
            return;
        }

        Mascota mascota = mascotaController.registrarMascota(tutor,
                texto(txtNombre), texto(txtEspecie), texto(txtEdad));
        if (mascota == null) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo registrar la mascota. Revise los datos.");
            return;
        }
        txtResultado.setText("Mascota registrada correctamente.\n"
                + describirMascota(mascota));
        limpiarCamposMascota();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (!controladoresDisponibles() || !camposMascotaCompletos()) {
            return;
        }

        Mascota mascota = solicitarMascotaDelTutor("Ingrese el ID de la mascota a modificar:");
        if (mascota == null) {
            return;
        }
        boolean modificada = mascotaController.modificarMascota(mascota,
                texto(txtNombre), texto(txtEspecie), texto(txtEdad));
        txtResultado.setText(modificada ? "Mascota modificada correctamente.\n"
                + describirMascota(mascota) : "No se pudo modificar la mascota.");
    }//GEN-LAST:event_btnModificarActionPerformed

    private Mascota solicitarMascotaDelTutor(String mensaje) {
        if (texto(txtDniBuscar).isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Ingrese primero el DNI del tutor.");
            return null;
        }
        String idIngresado = JOptionPane.showInputDialog(this, mensaje);
        if (idIngresado == null || idIngresado.trim().isEmpty()) {
            return null;
        }
        try {
            Mascota mascota = mascotaController.buscarMascotaPorId(
                    Integer.parseInt(idIngresado.trim()));
            if (mascota == null || mascota.getTutor() == null
                    || !texto(txtDniBuscar).equals(mascota.getTutor().getDni())) {
                JOptionPane.showMessageDialog(this,
                        "La mascota no existe o no pertenece al tutor indicado.");
                return null;
            }
            return mascota;
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El ID debe ser numerico.");
            return null;
        }
    }

    private String describirMascota(Mascota mascota) {
        return "ID: " + mascota.getIdMascota() + "\nNombre: "
                + mascota.getNombre() + "\nEspecie: " + mascota.getEspecie()
                + "\nEdad: " + mascota.getEdad();
    }

    private boolean camposMascotaCompletos() {
        if (texto(txtDniBuscar).isEmpty() || texto(txtNombre).isEmpty()
                || texto(txtEspecie).isEmpty() || texto(txtEdad).isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Complete DNI del tutor, nombre, especie y edad.");
            return false;
        }
        return true;
    }

    private boolean controladoresDisponibles() {
        if (tutorController == null || mascotaController == null) {
            JOptionPane.showMessageDialog(this,
                    "La vista debe abrirse desde Dashboard.");
            return false;
        }
        return true;
    }

    private String texto(javax.swing.JTextField campo) {
        return campo.getText().trim();
    }

    private void limpiarCamposMascota() {
        txtNombre.setText("");
        txtEspecie.setText("");
        txtEdad.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDniBuscar;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
